labels: ["product/editor-v4"]
body:
    - type: markdown
      attributes:
          value: |
              > [!NOTE]
              > **About this form:**
              >
              > Some of the links in this example form are not clickable or not working on purpose. The final form will have all the links pointing to the correct destinations.
              >
              > This is just a preview, and this note will not be part of the final form.

              # 🧪 Editor V4 Discussion Form
              <br>

              👋 **Welcome, and thank you for helping shape the future of Elementor!**

              We’re thrilled to have you here testing **Editor V4** — a major evolution of the Elementor Editor, rebuilt to improve performance, responsiveness, and your overall workflow.

              This space is for sharing your thoughts, insights, and suggestions about Editor V4's experimental features. Your feedback is incredibly valuable and helps guide the direction of the product during its development.

              Want to learn more about Editor V4? **[Visit our Editor V4 landing page](https://elemn.to/editor-v4)**, it will be updated regularly!
              <br>
              <br>

              ## 🧭 Guidelines

              Before getting started, please review our **[Contribution Guidelines](#)** and **[Code of Conduct](#)**. These documents help us maintain a respectful, inclusive, and organized space for all contributors.

              > [!IMPORTANT]
              > ### 🧪 This space is dedicated to discussing features in Editor V4.
              > 
              > If you're here to report a bug, please use the 🐛 **[Editor V4 Bug Report Form](#)**.  
              > Keep in mind that the **Editor V4** is still in early development — it may not include all existing features from Elementor V3 and is subject to change or instability.  
              > For common questions, check the ❔ **[Editor V4 FAQ](#)**.  
              > 
              > If your topic is not related to Editor V4, please use one of the 🔗 **Quick Links** below to find the right space for it.
              <br>

              ## 💡 Help Us Keep Discussions Organized

              - 🔍 **Search for existing discussions.** <br>Someone may have already started a thread on your topic. Add your thoughts there to keep conversations centralized.

              - ✒️ **Use a clear and descriptive title.** <br>A good title helps others quickly understand what your post is about.

              - ☝️ **Stick to one topic per discussion thread.** <br>This makes it easier to track feedback and follow up on specific subjects.
    - type: textarea
      id: discussion
      validations:
          required: true
      attributes:
          description: "Please share your thoughts, feedback, or questions below."
          placeholder: "Start a discussion..."
    - type: markdown
      attributes:
          value: |
              <br>

              ----
              ## 🔗 Quick Links

              Need something else? These links will help you get support, learn, or contribute in the right place:

              - 🛟 **Get Personal Support** — Need help or guidance? https://elemn.to/support-ticket

              - 🔧 **Fix Common Issues** — Troubleshoot the most frequent problems. https://elemn.to/help-troubleshooting

              - 📑 **Help Center** — Documentation, FAQs, and useful articles. https://elemn.to/help

              - 🎓 **Elementor Academy** — Learn how to use Elementor like a pro. https://elemn.to/academy

              - 💬 **Discord Community** — Chat with other Web Creators. https://elemn.to/discord

              - 🌍 **Facebook Community** — Help and get help from other Elementor users. https://elemn.to/community-on-fb

              - 🌐 **Developers Community** — Share code tips and ask other devs about extending with Elementor. https://elemn.to/dev-community

              - 📚 **Developers Center** — For extending Elementor via API or custom code. https://elemn.to/dev-center

              - 🚀 **Feature Requests** — Suggest new ideas or improvements. https://elemn.to/gh-feature-requests

              - 🚩 **Elementor Roadmap** — Check what’s coming next. https://elemn.to/roadmap

              - 🐛 **Editor V4 Bug Reports** — Report issues with **Editor V4**. [https://elemn.to/editor-v4-bugs](#)

              - ❔ **Editor V4 FAQ** — Read the most frequent questions about **Editor V4**. [https://elemn.to/editor-v4-faq](#)

              - 📖 **Contribution Guidelines** — Learn how to contribute to this repository. https://elemn.to/gh-contributing

              - 🤝 **Code of Conduct** — Help us foster a respectful and inclusive environment. https://elemn.to/gh-code-of-conduct

              - 🛡️ **Security Policy** — Report vulnerabilities safely. https://elemn.to/gh-security
    - type: checkboxes
      id: final_agreement
      attributes:
          label: "Agreement"
          description: "By filling out this form, you confirm that you have read the guidelines outlined above, and you agree that your discussion may be closed without warning if it doesn't meet them."
          options:
              - label: "I confirm I have read and followed the guidelines, and agree this discussion may be closed without warning."
                required: true
