name: "🐛 Report a Confirmed Bug in Editor V4"
description: "Report confirmed bugs in Editor V4's experimental features and help us improve the experience before release."
labels: ["status/awaiting_triage", "product/editor-v4"]
body:
    - type: markdown
      attributes:
          value: |
              > [!NOTE]
              > **About this form:**
              >
              > Some of the links in this example form are not clickable or not working on purpose. The final form will have all the links pointing to the correct destinations.
              >
              > This is just a preview, and this note will not be part of the final form.

              # 🐛 Report a Confirmed Bug in Elementor Editor V4
              <br>

              👋 **Welcome, and thank you for helping shape the future of Elementor!**

              We’re excited to introduce the **Editor V4** — a refreshed foundation for the Elementor Editor that improves performance, responsiveness, and workflow experience.

              Your feedback is incredibly valuable. Use this form to report bugs related to Editor V4’s experimental features. Every report helps us create a better product before its full release.
              <br>
              <br>

              ## 🧭 Guidelines

              Before getting started, please take a moment to review our **[Contribution Guidelines](#)** and **[Code of Conduct](#)**. These help us keep this space respectful, organized, and inclusive for everyone.

              > [!IMPORTANT]
              > ### 🐛 This form is for reporting <ins>confirmed bugs in Editor V4</ins> experimental features only.
              > Please only use this form if you've already investigated and confirmed that the issue is caused specifically by Editor V4 components.
              > If your issue is unrelated to Editor V4 features, or if you're here for another reason please **[use our general 🐞 Bug Report form instead](#)**.
              >
              > Keep in mind the **Editor V4** is a work in progress and should not be used on production sites. It may not include all features from Elementor V3 and is subject to changes or instability during development.
              >
              > 🧪 For discussing and sharing feedback about the Editor V4, please go to the dedicated Discussion Category instead: **[Discuss the Editor V4](#)**
              >
              > ❔ For frequent questions, check the **[Editor V4 FAQ](#).**
              >
              > ⚠️ _**Reports that are unrelated to Editor V4 or missing required information may be closed without further review.**_
              <br>

              ### 📋 Requirements

              For a quick review and efficient resolution, please ensure your report meets the following requirements:

              - *️⃣ **All fields in this form are required** — no exceptions. <br>Incomplete issues will be closed without further action.

              - 🔍 **Search for similar issues before opening a new one.** <br>Avoid duplicates and save time by using the **[editor-v4](https://github.com/elementor/elementor/labels/product%2Feditor-v4)** label to narrow your search.

              - 🗑️ **Clear all relevant cache layers.** <br>Confirm the issue is not being caused by stale or cached data. <br>Please clear server cache, site-level cache (including plugin-based cache), CDN cache, and your browser cache — in that order.

              - 🕵️ **Test with only Elementor, Elementor Pro, and the Hello Theme active.** <br>Temporarily disable all other plugins and themes. This step helps confirm that the issue is not being caused by a 3rd-party conflict. <br>👉 Reference: **[Troubleshooting the Editor](https://elemn.to/help-troubleshooting)**

              - 💾 **Copy and paste your complete Elementor System Info.** <br>This is not optional and helps us better reproduce and understand your issue. Reports without the full Elementor System Info will be closed. <br>👉 Learn how to copy it here: **[Share system information with Elementor](https://elemn.to/help-system-info)**

              - 🪪 **If you’re a 3rd-party developer**, please introduce yourself. <br>Include your name, company, product name, and a way for us to contact you (such as an email address) if needed. <br>This helps us collaborate more effectively.

              - ☝️ **Only one issue per report.** <br>Please don’t bundle multiple bugs in a single submission. This helps us track, reproduce, and fix each issue accurately.
              <br>
              <br>

              ### 🎯 Scope

              To keep this repository focused and efficient, there are some types of reports that we are unable to handle here. These types of issues will be **closed without further action**. 

              - 🐞 **Issues unrelated to bugs in the Editor V4.** <br>If you're here to report issues with existing features of Elementor V3, please **[use our general 🐞 Bug Report form instead](#)**.

              - 🛟 **Requests for personal support** <br>This includes help with setup, troubleshooting, or usage guidance. For that, please contact our **[official support channels](https://elemn.to/support-ticket)**.

              - 🧩 **Conflicts with 3rd-party plugins, themes, or services.** <br>We’re only able to address issues related to Elementor and Elementor Pro directly. If the problem occurs when using a plugin, theme, or integration that is not officially supported by Elementor, please reach out to the 3rd-party provider for assistance.

              - 🚀 **Feature requests or suggestions.** <br>We love your ideas! But this form is only for confirmed bugs. Please use the dedicated Feature Request form instead. <br>See: **[Request a Feature](#)**

              - 📚 **Questions about custom code or extending Elementor.** <br>We cannot provide assistance with writing or debugging custom code. If you’re building with the Elementor API, we recommend using our **[Developers Documentation](https://elemn.to/dev-docs)**.

              - 🛡️ **Security and vulnerability disclosures.** <br>We take security seriously. Please use our managed [Bug Bounty Programs](https://elemn.to/bug-bounty) to responsibly report security issues.

              - ☹️ **Complaints or offensive content.** <br>This is not the place to submit complaints about Elementor’s products or services. We also do not tolerate offensive, discriminatory, or hostile remarks. Please keep discussions respectful as outlined in our **[Code of Conduct](#)**.

              - ❌ **Incomplete, invalid, or out-of-scope reports.** <br>Issues without clear steps to reproduce, missing required fields, or unrelated to Elementor or Elementor Pro will be closed without further action.
              <br>

              ----

              ## 📝 Instructions

              To make it easier for the team to understand and resolve your issue, please follow these best practices:

              - ✒️ **Use a clear and descriptive title** <br>A good title helps everyone quickly understand what the issue is about. Try to summarize the problem in a few words.

              - 💬 **Describe the issue in detail.** <br>Include as much context as you can. What happened? When did it start? What page or feature does it affect? <br>Feel free to attach screenshots or screen recordings — just drag and drop them into the text field when filling out the form.

              - 👣 **List all steps to reproduce the issue.** <br>Be specific! We need to follow the exact steps you took to reproduce the issue — ideally on a clean WordPress installation. <br>Reports without clear reproduction steps may be closed, as we cannot fix what we cannot replicate.

              - 🧠 **Explain what you expected to happen.** <br>Help us understand what you believe the correct or intended behavior should be. If you were expecting a feature that does not exist, it might not be a bug — in that case, please submit a Feature Request instead. You can find the link in the 🔗 **Quick Links** section.
    - type: textarea
      id: description
      validations:
          required: true
      attributes:
          label: "Description"
          description: "Please describe the issue in detail and include as much context as possible. Feel free to attach screenshots or screen recordings — just drag and drop them into the field below."
          placeholder: "Examples: \nChanging a Global Class in the Class Manager doesn't update all linked elements... \nThe Style Indicator shows conflicting styles even when no class is applied... \nThe Actions Bar doesn't appear when hovering over a nested Flex Container... \nDevice-specific padding settings are not saving correctly on Tablet... \nDragging to reorder backgrounds in Style Repeaters breaks the visual order..."
    - type: textarea
      id: steps_to_reproduce
      validations:
          required: true
      attributes:
          label: "Steps to reproduce"
          description: "List all steps to reproduce the issue. Be specific! We need to follow the exact steps you took to reproduce the issue, ideally on a clean WordPress installation."
          placeholder: "Examples: \n1. In the WordPress Dashboard, go to... \n2. Create a Template... \n3. Drag & Drop the widget... \n4. Save the post and click on preview..."
    - type: textarea
      id: expected_behavior
      validations:
          required: true
      attributes:
          label: "Expected behavior"
          description: "Explain what you expected to happen. Help us understand what you believe the correct or intended behavior should be. This helps us identify the root of the issue faster."
          placeholder: "Examples: \n1. When I apply a style to {widget} I expect it to... \n2. According to the Documentation in the Help Center... \n3. ..."
    - type: markdown
      attributes:
          value: |
              ### 💾 Elementor System Info
              ⚠️ **<ins>This field is REQUIRED and it is NOT OPTIONAL</ins>**
              - Please copy and paste the **<ins>full Elementor System Info</ins>** report from your WordPress **`Dashboard`** → **`Elementor`** → **`System Info`** page (available at the bottom of the page). <br>**We won't accept issues without it. [Learn how to copy it here](https://elemn.to/help-system-info).**
    - type: textarea
      id: system_info
      validations:
          required: true
      attributes:
          label: "Elementor System Info"
          description: "Redact or remove sensitive information (like admin email, or root paths) if necessary. Keep other details, as these are vital for understanding your problem and recreating it correctly."
          placeholder: "== Server Environment == \n== WordPress Environment == \n== Theme == \n== User == \n== Active Plugins == \n== Elements Usage == \n== Settings == \n== Features == \n== Integrations == \n== Elementor Experiments == \n== Log == \n== Elementor - Compatibility Tag == \n== Elementor Pro - Compatibility Tag =="
          render: txt
    - type: markdown
      attributes:
          value: |
              <br>

              ----
              ## 🔗 Quick Links

              Need something else? These links will help you get support, learn, or contribute in the right place:

              - 🛟 **Get Personal Support** — Need help or guidance? https://elemn.to/support-ticket

              - 🔧 **Fix Common Issues** — Troubleshoot the most frequent problems. https://elemn.to/help-troubleshooting

              - 📑 **Help Center** — Documentation, FAQs, and useful articles. https://elemn.to/help

              - 🎓 **Elementor Academy** — Learn how to use Elementor like a pro. https://elemn.to/academy

              - 💬 **Discord Community** — Chat with other Web Creators. https://elemn.to/discord

              - 🌍 **Facebook Community** — Help and get help from other Elementor users. https://elemn.to/community-on-fb

              - 🌐 **Developers Community** — Share code tips and ask other devs about extending with Elementor. https://elemn.to/dev-community

              - 📚 **Developers Center** — For extending Elementor via API or custom code. https://elemn.to/dev-center

              - 🐞 **General Bug Reports** — Report confirmed bugs in Elementor V3. https://elemn.to/gh-issues

              - 🚀 **Feature Requests** — Suggest new ideas or improvements. https://elemn.to/gh-feature-requests

              - 🚩 **Elementor Roadmap** — Check what’s coming next. https://elemn.to/roadmap

              - 🧪 **Editor V4 Discussion** — Share your feedback! [https://elemn.to/editor-v4-discussion](#)

              - ❔ **Editor V4 FAQ** — Read the most frequent questions about **Editor V4**. [https://elemn.to/editor-v4-faq](#)

              - 📖 **Contribution Guidelines** — Learn how to contribute to this repository. https://elemn.to/gh-contributing

              - 🤝 **Code of Conduct** — Help us foster a respectful and inclusive environment. https://elemn.to/gh-code-of-conduct

              - 🛡️ **Security Policy** — Report vulnerabilities safely. https://elemn.to/gh-security
    - type: checkboxes
      id: final_agreement
      attributes:
          label: "Agreement"
          description: "By filling out this form, you confirm that you have read and followed the guidelines and instructions outlined above, and you agree that your issue may be closed without further action if it doesn't meet them."
          options:
              - label: "I confirm I have read and followed all the guidelines and instructions outlined in the Editor V4 Bug Report form."
                required: true
              - label: "I agree that my issue may be closed without further action if it doesn't meet all the requirements outlined in the Editor V4 Bug Report form."
                required: true
    - type: markdown
      attributes:
          value: |
              <br>

              ---
              ### 🙏 Thank you for contributing and helping make Elementor better.
