name: "🐞 Report a Bug in Elementor"
description: "Did you find a bug in the source code of Elementor, and can reproduce it consistently after troubleshooting it? Report it here."
labels: ["status/awaiting_triage"]
body:
    - type: markdown
      attributes:
          value: |
              **👋 Welcome! Thank you for contributing!**
              <br>

              > [!WARNING]
              >  ## ⚠️ ATTENTION! Before continuing, please, read these instructions carefully!
              > _Failing to follow these guidelines may result in closing your issue without any action._
              <br>

              ### 🐞 This Form is exclusive for reporting <ins>Confirmed Bugs</ins> in the Elementor, and Elementor Pro plugins
              **While we welcome contributions, please only use this form to report Bugs in the Elementor Editor that you have troubleshooted, isolated, and can reproduce consistently.**
              - *️⃣ **All fields are required, <ins>without execption</ins>.**
              - 💾 **The inclusion of the [Elementor System Info](https://elemn.to/help-system-info) <ins>is not optional.</ins>**
              <br>

              ### ❌ Invalid Issues will be closed
              - 🛟 **Personal Support Requests will be closed without any action.** <br>We are unable to provide and appropriately track Personal Support requests from this repository. Use the official support channels if you need assistance.
              - 🧩 **3rd-Party conflicts or bugs will be closed without any action.** <br>We do not provide solutions or support for 3rd-party code, addons, extensions, plugins, themes, or services that Elementor does not offer official integration or support. In this case contact the 3rd-party sofware support instead. **Support for Custom Code is out of scope.**
              - ☹️ **Complaints will be closed without any action.** <br>This is not the place for submitting this kind of feedback. We are unable to track them and take action. Reach out to Elementor Support instead.
              - 🐞 **Invalid Issues will be closed without any action.** <br>Issues lacking detail, without required information, or submitted for any other reason other than to report confirmed and reproducible bugs specific to the Elementor, and Elementor Pro plugins will be closed without any action.
              <br>

              ### 💡 Follow these best practices to help save time
              - ✒️ **Always Provide a Clear and concise Title.** <br>Please provide a clear and concise title that can be easily identifiable. Anyone must understand what the problem is by only reading the title.
              - 💬 **Make a Detailed Description.** <br>In your description, provide examples, screenshots, and screen recordings (just drag and drop the files into the text field), and save time by describing in detail what happened. The more information you provide, the faster we can find a solution!
              - 👣 **List all the Steps to Reproduce your Issue.** <br>We need to be able to reproduce your issue consistently in order to validate it. Provide all the steps that you took to experience the issue so we can reproduce it on our own. Don't leave anything out. If we can't reproduce it, we will close the issue.
              - 🗑️ **Clear All Levels of Cache.** <br>Ensure all levels of cache have been purged, cleared, and deactivated to avoid interferances or conflicts. This includes but is not limited to server cache, site cache, CDN cache, and browser cache.
              - ☝️ **Write Only One Issue Per Thread.** <br>If you are experiencing more than one bug, submit only **<ins>ONE ISSUE PER THREAD</ins>**, this way we can properly track them and reference them without any confusion. Issues with multiple reports will be closed.
              <br>
              
              ### 🔗 Quick links
              - 🛟 Need Help, Guidance, Assistance, or **Personal Support**? [Click here to learn how to get Personal Support](https://elemn.to/support-ticket).
              - 🔧 Before submitting your issue, **troubleshoot and validate it.** [Click here to start troubleshooting common issues](https://elemn.to/help-troubleshooting).
              - 🛡️ For **Security Reports**, please follow the instructions in our [Security Policy](https://elemn.to/gh-security-policy). **Do not submit Security Reports here.**
              - 📚 For information about **extending Elementor**, please [visit our Developers Center](https://elemn.to/gh-to-dev-center).
              <br>

              ### ℹ️ For more information about how to contribute, please read our [Contribution Guidelines](https://elemn.to/gh-contributing). 
              **<ins>We expect you to follow them while submitting your issue.</ins>**
              <br>

              ----

              ## THE ISSUE
              ### Prerequisites
              - 🔍 **Search Before Posting:** Before creating a new Bug Report, please **[search for similar issues](https://github.com/elementor/elementor/issues/)** to prevent unecessary duplicates. <br>Use **[GitHub Labels](https://elemn.to/gh-labels)** to refine your search.
              - 🆕 **Stay Up-to-date** <br>Ensure you are using the **[most recent and stable versions of Elementor (and Elementor Pro)](https://elemn.to/changelog)**, as well as all installed plugins, themes, and even WordPress.
    - type: checkboxes
      id: prerequisites
      attributes:
          label: "Prerequisites"
          options:
              - label: "I have searched for similar issues in open and closed tickets and cannot find a duplicate."
                required: true
              - label: "I have troubleshooted my issue, and it still exists against the latest stable version of Elementor."
                required: true
    - type: markdown
      attributes:
          value: |
              <br>

              ### 💬 Provide a Detailed Description
              Please describe the problem in detail, provide examples, screenshots, and related links.
    - type: textarea
      id: description
      validations:
          required: true
      attributes:
          label: "Description"
          description: "Please help us understand in detail what problems you are experiencing."
    - type: markdown
      attributes:
          value: |
              <br>

              ### 👣 Steps to Reproduce
              Enumerate all the steps needed to reproduce the issue in detail so we can replicate it in our environment. 
              - Be thorough. We will only be able to reproduce your issue if you thoroughly explain all the steps to replicate it. 
              - Please **share a screen recording**. It helps a lot!
    - type: textarea
      id: steps_to_reproduce
      validations:
          required: true
      attributes:
          label: "Steps to reproduce"
          description: "Provide steps that we can recreate on our own."
          placeholder: "1. ... \n2. ... \n3. ..."
    - type: markdown
      attributes:
          value: |
              <br>

              ### 🧐 Expected Behavior
              Describe the expected behavior to help identify the root of the issue.
    - type: textarea
      id: expected_behavior
      validations:
          required: true
      attributes:
          label: "Expected behavior"
          description: "Please help us understand what you are expecting to happen."
          placeholder: "1. ... \n2. ... \n3. ..."
    - type: markdown
      attributes:
          value: |
              <br>

              ### 🕵️ Isolate the problem and Validate your issue
              - Deactivate all plugins _**except Elementor (and Elementor Pro)**_, and temporarily change the theme to the **[Hello Elementor themes](https://wordpress.org/themes/hello-elementor/)**.
              - Verify if your problem happens when only the Elementor (and Elementor Pro) plugins are active while also using the Hello Elementor themes.
              - If the issue can't be recreated consistently or reproduced following the steps above, it's likely **not an Elementor bug**. <br>In that case, use the **[support link](https://elemn.to/support-ticket)** at the top of this form, or **[troubleshoot your issue again](https://elemn.to/help-troubleshooting)**.
    - type: checkboxes
      id: isolating_the_problem
      attributes:
          label: "Isolating the problem"
          options:
              - label: "This bug happens when only the Elementor (and Elementor Pro) plugins are active."
              - label: "This bug happens with the Hello Elementor theme active."
              - label: "I can reproduce this bug consistently by following the steps I described above."
    - type: markdown
      attributes:
          value: |
              <br>

              ### 💾 Elementor System Info
              **⚠️ <ins>This field is REQUIRED</ins>**
              - Please copy and paste the **<ins>full Elementor System Info</ins>** report from your WordPress **`Dashboard`** > **`Elementor`** > **`System Info`** page (available at the bottom of the page). <br>**We won't accept issues without it. [Learn how to copy it here](https://elemn.to/help-system-info).**
    - type: textarea
      id: system_info
      validations:
          required: true
      attributes:
          label: "Elementor System Info"
          description: "Redact or remove sensitive information (admin email, website links, or root paths) if necessary. Keep other details, as these are vital for understanding your problem and recreating it correctly."
          placeholder: "== Server Environment == \n== WordPress Environment == \n== Theme == \n== User == \n== Active Plugins == \n== Elements Usage == \n== Settings == \n== Features == \n== Integrations == \n== Elementor Experiments == \n== Log == \n== Elementor - Compatibility Tag == \n== Elementor Pro - Compatibility Tag =="
          render: txt
    - type: markdown
      attributes:
          value: |
              <br>

              ### 📃 Agreement
              ⚠️ **Please follow all the instructions above** and fill in all the required fields with valid information. 
              ⛔ **As a gentle reminder, we may close issues that do not comply with these guidelines without action.**
    - type: checkboxes
      id: final_agreement
      attributes:
          label: "Agreement"
          options:
              - label: "I agree that my issue may be closed without action if it doesn't meet all the requirements."
                required: true
    - type: markdown
      attributes:
          value: |
              <br>

              ---
              ### 🙏 Thank you for contributing and helping make Elementor better.
